### ISSUE TITLE
Sanity check , as the prior step to SATAY , with the transformed strains 

### ISSUE THREAD

**Issue by leilaicruz** [T-Wisse/MEP_Thomas#20]
## Decisions and actions (*Therefore we will...*)

**Comment by T-Wisse** [comment]
Hypothesis (We believe that...)
We can find good colonies for SATAY by checking if colonies of the transformed yTW001 and yLIC137 strains indeed contain the plasmid for SATAY

Test (To verify that we will...)
To verify that for each strain we will take 8 of the colonies that form on the selection plate and restreak these onto both -Ade and -Ura plates. 

False Test (To falsify that we should test...)


Metric (And measure...)

Criteria (We are right if...)
We are right if we observe a small number of colonies on the -Ade and an normal number of colonies on the -Ura plate. This should occur because in some (but very few) of the plasmids the Ade2 gene should be repaired, allowing for growth on -Ade if the plasmid is present. The plasmid also contains the ura gene, allowing for normal growth on -Ura if present.

Observation (We observed...)
Some white colonies were present for a few (3) of the streaks on the -ADE plates for yTW001 and for multiple of the streaks on the -ADE of yLIC137. The corresponding -Ura plates generally showed colonies too, in larger number.

Learnings and insights (From that we learned that...)
From that we learned that some of the colonies from the transformation have succesfully obtained the plasmid and some cells have repaired the ADE2 gene.

Decisions and actions (Therefore we will...)
Therefore we will use the colonies on the -URA plates that correspond to some growth on the -ADE plates for the preculture of SATAY
